//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPlan.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applications()
        {
            this.FinalPlan = new HashSet<FinalPlan>();
        }
    
        public int ID_application { get; set; }
        public Nullable<int> ID_goods { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> ID_status { get; set; }
        public Nullable<int> ID_department { get; set; }
        public Nullable<int> ID_creator { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> year1price { get; set; }
        public Nullable<decimal> year2price { get; set; }
        public Nullable<decimal> year3price { get; set; }
        public Nullable<decimal> yearAprice { get; set; }
        public decimal TotalPrice => (decimal)(Количество * Goods.Цена.Value);
        public virtual Departments Departments { get; set; }
        public virtual Goods Goods { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalPlan> FinalPlan { get; set; }
    }
}
