//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPlan.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applications()
        {
            this.MainPlan = new HashSet<MainPlan>();
        }
    
        public int ID_application { get; set; }
        public int ID_goods { get; set; }
        public string Количество { get; set; }
        public int ID_status { get; set; }
        public int ID_department { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Status Status { get; set; }
        public virtual Goods Goods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPlan> MainPlan { get; set; }
    }
}
