//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPlan.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalPlan
    {
        public int ID_finalplan { get; set; }
        public int ID_application { get; set; }
    
        public virtual Applications Applications { get; set; }
    }
}
