//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkPlan.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainPlan
    {
        public int ID_inplan { get; set; }
        public int ID_application { get; set; }
        public Nullable<System.DateTime> Дата_утверждения { get; set; }
        public string Год_исполнения { get; set; }
    
        public virtual Applications Applications { get; set; }
    }
}
